# Generated by Django 4.0.1 on 2022-01-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JPNIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名前')),
                ('is_active', models.BooleanField(blank=True, verbose_name='有効')),
                ('is_ipv6', models.BooleanField(verbose_name='IPv6')),
                ('asn', models.IntegerField(verbose_name='ASN')),
                ('ca_path', models.CharField(default='', max_length=200, verbose_name='中間CA証明書')),
                ('cert_path', models.CharField(default='', max_length=200, verbose_name='Cert')),
                ('key_path', models.CharField(default='', max_length=200, verbose_name='key')),
                ('p12_path', models.CharField(default='', max_length=200, verbose_name='P12')),
                ('p12_pass', models.CharField(default='', max_length=200, verbose_name='P12 Pass')),
            ],
            options={
                'verbose_name': 'AS',
                'verbose_name_plural': 'AS',
            },
        ),
    ]
