# Generated by Django 4.1 on 2023-03-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jpnic_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="取得開始時刻")),
                ("last_checked_at", models.DateTimeField(db_index=True, verbose_name="最終更新時刻")),
                (
                    "type1",
                    models.CharField(
                        choices=[("資源情報", "資源情報"), ("アドレス情報", "アドレス情報")], max_length=200, verbose_name="type1"
                    ),
                ),
                ("count", models.IntegerField(verbose_name="リクエスト回数")),
                ("fail_count", models.IntegerField(verbose_name="リクエスト失敗回数")),
                ("fail_result", models.CharField(max_length=200, verbose_name="失敗理由")),
                ("jpnic", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="jpnic_admin.jpnic")),
            ],
            options={
                "ordering": ("-last_checked_at",),
                "index_together": {
                    ("created_at", "last_checked_at", "type1", "jpnic_id"),
                    ("last_checked_at", "type1", "jpnic_id"),
                },
            },
        ),
    ]
