# Generated by Django 5.2.15 on 2026-06-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpnic_admin', '0001_initial'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at', 'last_checked_at', 'type1', 'jpnic'], name='task_created_checked_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['last_checked_at', 'type1', 'jpnic'], name='task_checked_idx'),
        ),
        migrations.AddIndex(
            model_name='taskerror',
            index=models.Index(fields=['created_at', 'task'], name='taskerror_created_task_idx'),
        ),
    ]
