# Generated by Django 4.2.1 on 2023-05-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrlist',
            name='abuse',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Abuse'),
        ),
        migrations.AlterField(
            model_name='addrlist',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='addrlist',
            name='address_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='住所(英語)'),
        ),
        migrations.AlterField(
            model_name='addrlist',
            name='apply_from_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='申請者メールアドレス'),
        ),
        migrations.AlterField(
            model_name='addrlist',
            name='ds_record',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='DSレコード'),
        ),
        migrations.AlterField(
            model_name='addrlist',
            name='nameserver',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ネームサーバ'),
        ),
        migrations.AlterField(
            model_name='addrlist',
            name='notify_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='通知アドレス'),
        ),
        migrations.AlterField(
            model_name='addrlist',
            name='org',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='組織名'),
        ),
        migrations.AlterField(
            model_name='addrlist',
            name='org_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='組織名(英語)'),
        ),
        migrations.AlterField(
            model_name='addrlist',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='addrlist',
            name='recep_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='受付番号'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='address_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='住所(英語)'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='apply_from_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='申請者メールアドレス'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='division',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='division_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='部署(英語)'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='名前(英語)'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='notify_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='通知アドレス'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='org',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='組織名'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='org_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='組織名(英語)'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='recep_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='受付番号'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='tel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='肩書'),
        ),
        migrations.AlterField(
            model_name='jpnichandle',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='肩書(英語)'),
        ),
    ]
