# Generated by Django 4.2.1 on 2023-06-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_alter_addrlist_abuse_alter_addrlist_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceaddresslist',
            name='all_addr_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='アドレス数'),
        ),
    ]
