version: '3'
services:
  jpnic-admin:
    container_name: jpnic-admin
    image: yoneyan/jpnic-admin:develop
    ports:
      - "80:80"
    environment:
      - DJANGO_SETTINGS_MODULE=jpnic_admin.production_settings
      - SKIP_SUPERUSER=false
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_NAME=admin
      - SUPERUSER_PASSWORD=test123#
      - DB_NAME=jpnic-admin
      - DB_USER=jpnic-admin
      - DB_PASSWORD=passWord123#
    volumes:
      - ./config:/opt/app/config
    links:
      - db
      - daemon
    restart: always
  db:
    image: mariadb:10.7.4
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql-jpnic-admin:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=PassWOrd123#
      - MYSQL_DATABASE=jpnic-admin
      - MYSQL_USER=jpnic-admin
      - MYSQL_PASSWORD=passWord123#
  daemon:
    image: yoneyan/jpnic-admin-daemon:develop
    environment:
      - CA_URL=http://jpnic-admin:8000/ca
      - DATABASE_TYPE=mysql
      - DATABASE_IP=db
      - DATABASE_NAME=jpnic-admin
      - DATABASE_USER=jpnic-admin
      - DATABASE_PASS=passWord123#
    links:
      - db
    restart: always