# Generated by Django 5.2.15 on 2026-06-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('jpnic_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='addrlist',
            index=models.Index(fields=['jpnic', 'network_name', 'address', 'address_en', 'ip_address', 'admin_handle', 'assign_date', 'type', 'division'], name='addr_full_idx'),
        ),
        migrations.AddIndex(
            model_name='addrlist',
            index=models.Index(fields=['created_at', 'last_checked_at', 'jpnic', 'network_name', 'address', 'address_en'], name='addr_created_checked_idx'),
        ),
        migrations.AddIndex(
            model_name='addrlist',
            index=models.Index(fields=['last_checked_at', 'jpnic', 'network_name', 'address', 'address_en'], name='addr_checked_idx'),
        ),
        migrations.AddIndex(
            model_name='jpnichandle',
            index=models.Index(fields=['created_at', 'last_checked_at', 'jpnic_handle', 'jpnic'], name='handle_created_checked_idx'),
        ),
        migrations.AddIndex(
            model_name='jpnichandle',
            index=models.Index(fields=['last_checked_at', 'jpnic_handle', 'jpnic'], name='handle_checked_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelist',
            index=models.Index(fields=['created_at', 'last_checked_at', 'jpnic'], name='res_created_checked_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelist',
            index=models.Index(fields=['last_checked_at', 'jpnic'], name='res_checked_idx'),
        ),
    ]
