name: Publish Docker image(prod)

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    paths:
    - '.github/**'
    - 'files/**'
    - 'jpnic_admin/**'
    - 'manage.py'
    - 'Dockerfile'
    - 'requirements.txt'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/homenoc/jpnic_admin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platform: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/homenoc/jpnic_admin:${{ env.TAG_NAME }}
            ghcr.io/homenoc/jpnic_admin:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create Changelog
        id: create_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configurationJson: |
            {
               "template": "## Commit Log \n #{{UNCATEGORIZED}} \n\n **Full Change Log**: #{{RELEASE_DIFF}}",
               "pr_template": "- #{{TITLE}} by @#{{AUTHOR}} in ##{{NUMBER}}",
               "sort": {
                 "order": "DESC",
                 "on_property": "mergedAt"
               }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.create_changelog.outputs.changelog }}